### ISSUE TITLE
Anime Support 

### ISSUE THREAD

**Issue by nyouness** [nktfh100/stremio-simkl#1]
Hii , thank you a loot for making this addon , can you please add support for anime and if possible make it based on Kitsu anime addon .
![Screenshot 2023-12-31 141245](https://github.com/nktfh100/stremio-simkl/assets/117232906/48613451-6b7b-4b86-8163-78b8da688ea0)

**Comment by nktfh100** [comment]
Hey currently I have no plans for adding anime support, but you are welcome to add this feature yourself!
